// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName
import { application } from "./application"
import Dialog from '@stimulus-components/dialog'
application.register('dialog', Dialog)

import ActionItems__FormController from "./action_items/form_controller"
application.register("action-items--form", ActionItems__FormController)

import ActionItems__ListsController from "./action_items/lists_controller"
application.register("action-items--lists", ActionItems__ListsController)

import ActionItems__PresentTagsController from "./action_items/present_tags_controller"
application.register("action-items--present-tags", ActionItems__PresentTagsController)

import Charts__DisplayController from "./charts/display_controller"
application.register("charts--display", Charts__DisplayController)

import DailyRecords__MoodScoreController from "./daily_records/mood_score_controller"
application.register("daily-records--mood-score", DailyRecords__MoodScoreController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import PasswordFieldController from "./password_field_controller"
application.register("password-field", PasswordFieldController)

import RangeSlider__CurrentMoodController from "./range_slider/current_mood_controller"
application.register("range-slider--current-mood", RangeSlider__CurrentMoodController)

import StepDialogController from "./step_dialog_controller"
application.register("step-dialog", StepDialogController)
