// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import Charts__DisplayController from "./charts/display_controller"
application.register("charts--display", Charts__DisplayController)

import DailyRecords__MoodScoreController from "./daily_records/mood_score_controller"
application.register("daily-records--mood-score", DailyRecords__MoodScoreController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import PasswordFieldController from "./password_field_controller"
application.register("password-field", PasswordFieldController)
